version: '3.8'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - example-db:/data/db
  
  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis:/data
  
  api:
    build: .
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  example-db:
  redis:
